### ISSUE TITLE
What does this loader do?

### ISSUE THREAD

**Issue by MiMaMuh** [webpack/style-loader#118] opened 2016-04-20 14:34 UTC
There is a simple explanation missing what this loader is for and what it does. Just two sentences would be awesome! Thx.

**Comment by meyer** [comment] 2016-04-22 01:17
@MiMaMuh The first two code blocks in the README are commented with a description of what the code does:

```js
require("style!raw!./file.css");
// add rules in file.css to document
```

In this case, the contents of `./file.css` will be added to the document.

**Comment by furkanedu** [comment] 2016-04-24 18:30
Still have no idea about what this loader is about ? How does it work ? Where does it load css rules etc. It would be great to hear a clear explanation.

**Comment by luisrudge** [comment] 2016-04-25 02:56
It loads all the rules inside the `<head>` tag with the proper `<style>` tag

**Comment by IAMtheIAM** [comment] 2016-05-17 21:19
What they mean is that it "inlines" the styles like `<style> all my styles embedded here </style>` - so they are not external but in the `<head>` of the document

**Comment by meyer** [comment] 2016-05-22 00:48
@luisrudge @MiMaMuh If you don’t understand how `style-loader` works or where it loads styles, you should probably read more about webpack before tackling specific loaders.

Have you got webpack running in your project already? If not, please do that before asking how a loader works. Once you wrap your head around the basics of webpack, `style-loader` (and every other loader) will make sense.

If you’re unsure where to begin, there are dozens (probably hundreds by now) of boilerplate projects that you can get running quite easily. I recommend very minimal boilerplate projects (webpack config + a few files).

`webpack-howto` by Pete Hunt is a good place to start: https://github.com/petehunt/webpack-howto

**Comment by furkanedu** [comment] 2016-05-23 06:53
thanks @meyer .

**Comment by SpaceK33z** [comment] 2016-10-29 10:42
Dupe of #70. Note that we're working on adding better description in readme's for loaders soon.

**Closed by SpaceK33z** 2016-10-29 10:42 UTC
