### ISSUE TITLE
Readme doesn't provide clear description of what the project does

### ISSUE THREAD

**Issue by stuartmemo** [webpack/style-loader#110] opened 2016-02-09 19:11 UTC
Being new to Webpack, I was trying to figure out the difference between `css-loader` and `style-loader`. I'm assuming `css-loader` reads the contents of a CSS file, while `style-loader` understands that the contents of the files is a style and should be added to your page as such? Would be nice to have a clear description in the readme. :rose:

**Comment by akomm** [comment] 2016-04-08 11:16
css loader just reads a css file, create a webpack module which contains the CSS-string read from file. It also finds css-specific imports/includes and read read those too (depending on include/exlude setting for the loader). style-loader injects a style-DOM-element containing the given string, which were read by css-loader.

**Comment by SpaceK33z** [comment] 2016-10-29 10:34
Dupe of #70.

**Closed by SpaceK33z** 2016-10-29 10:34 UTC
